#Minecraft server properties
#Wed Oct 08 12:58:28 CST 2025
allow-flight=true
allow-nether=true
difficulty=easy
enable-command-block=true
function-permission-level=2
gamemode=adventure
spawn-animals=false
spawn-monsters=false
spawn-npcs=false
spawn-protection=0
sync-chunk-writes=true
use-native-transport=true
motd=海战PVP模板交流群:925480142