#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon May 26 21:01:30 CST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined-main.zip
